### ISSUE TITLE
DB charset

### ISSUE THREAD

**Issue by olegkonev** [olegkonev/jul-command-project#1]
Vladimir or Alexey, please add this code:
```php
else {
    $this->db->set_charset("utf8mb4");
}
```
after the closing brace:
https://github.com/olegkonev/jul-command-project/blob/a620431a00d5cf6caf00ae6d21473cf2156e7092/core/DB.php#L16
In order to apply the correct DB encoding by default for all OS.
Thanks.

**Comment by vladimirbabaskin** [comment]
Ok, Oleg!
